'use strict';
const assert=require('node:assert/strict');const C=require('./v4-core.js');const T=2000000000000;let tests=[];
function test(name,fn){try{fn();tests.push({name,pass:true})}catch(e){tests.push({name,pass:false,error:e.message});process.exitCode=1}}
const seed=()=>C.seed(T);const step=(s,t,d={})=>C.reduce(s,t,d,T).state;
function meeting(id='spades'){let s=seed();for(const [t,d] of [['join',{id}],['ready',{}],['demo-fill',{}],['demo-meet',{}],['arrive',{}],['demo-end',{}]])s=step(s,t,d);return s}
function completed(id='spades',ids){let s=meeting(id),p=C.group(s);s=step(s,'report',{ids:ids||p.members.filter(x=>x!=='you')});return step(s,'demo-confirm')}
test('Initial schema valid',()=>assert(C.validate(seed())));
test('35 initial points sum from unique earned rewards',()=>assert.equal(C.points(seed()),35));
test('Eight actual fixture groups searchable',()=>assert.equal(C.search(seed(),{},T).length,8));
test('Cards alias resolves only Spades',()=>assert.deepEqual(C.search(seed(),{query:'cards'},T).map(p=>p.id),['spades']));
test('Case-insensitive multiword search',()=>assert.equal(C.search(seed(),{query:'CASUAL CHESS'},T)[0].id,'chess'));
test('Impossible search remains empty',()=>assert.equal(C.search(seed(),{query:'underwater pottery'},T).length,0));
test('30 minutes total includes wait, not only duration',()=>assert.equal(C.search(seed(),{budget:30},T).length,0));
test('Free-only filters every result',()=>assert(C.search(seed(),{free:true},T).every(p=>C.A(p.a).free)));
test('Sports category exact',()=>assert(C.search(seed(),{category:'Sports'},T).every(p=>C.A(p.a).family==='Sports')));
test('Radius filters without widening',()=>assert.equal(C.search(seed(),{radius:.25},T).length,2));
test('Start window filters',()=>assert.equal(C.search(seed(),{window:10},T).length,0));
test('Travel buffer prevents unreachable join',()=>{let s=seed();s.offset=13*60000;assert.throws(()=>step(s,'join',{id:'spades'}),/not enough time/)});
test('Joining occupies exactly one place, no points',()=>{let s=step(seed(),'join',{id:'spades'});assert.equal(C.count(C.group(s)),4);assert.equal(C.points(s),35)});
test('Join is not readiness',()=>assert.equal(C.readyCount(C.group(step(seed(),'join',{id:'spades'}))),0));
test('Two active groups prevented',()=>{let s=step(seed(),'join',{id:'spades'});assert.throws(()=>step(s,'join',{id:'coffee'}),/already/)});
test('Repeated same join prevented',()=>{let s=step(seed(),'join',{id:'spades'});assert.throws(()=>step(s,'join',{id:'spades'}),/already/)});
test('Early check-in rejected',()=>{let s=step(seed(),'join',{id:'spades'});assert.throws(()=>step(s,'arrive'),/window/)});
test('User readiness cannot certify other people',()=>{let s=step(seed(),'join',{id:'spades'});s=step(s,'ready');assert.equal(C.readyCount(C.group(s)),1);assert.equal(C.group(s).phase,'forming')});
test('Cannot skip meeting before minimum readiness',()=>{let s=step(seed(),'join',{id:'spades'});assert.throws(()=>step(s,'demo-meet'),/minimum/)});
test('Demo peers become ready only explicitly',()=>{let s=step(seed(),'join',{id:'spades'});s=step(s,'demo-fill');assert.equal(C.readyCount(C.group(s)),3);assert(!C.group(s).ready.includes('you'))});
test('Minimum ready starts ready phase, no points',()=>{let s=step(seed(),'join',{id:'spades'});s=step(s,'ready');s=step(s,'demo-fill');assert.equal(C.group(s).phase,'ready');assert.equal(C.points(s),35)});
test('No evidence awards at arrival or timer completion',()=>assert.equal(C.points(meeting()),35));
test('Empty after-round report rejected',()=>assert.throws(()=>step(meeting(),'report',{ids:[]}),/Select/));
test('Forged witness rejected',()=>assert.throws(()=>step(meeting(),'report',{ids:['not-a-member']}),/Select/));
test('Self-witness rejected',()=>assert.throws(()=>step(meeting(),'report',{ids:['you']}),/Select/));
test('Report by itself grants no points',()=>{let s=step(meeting(),'report',{ids:['maya','leo','sam']});assert.equal(C.points(s),35);assert.equal(C.group(s).phase,'pending')});
test('Peer confirmation requires prior self-report',()=>assert.throws(()=>step(meeting(),'demo-confirm'),/own attendance/));
test('Full cards completion grants Wild card and Plot twist, exactly 100 total',()=>{const s=completed();assert.equal(C.points(s),100);assert(s.earned.includes('wild'));assert(s.earned.includes('plot'));assert.equal(s.history.length,1)});
test('Repeated confirmation awards nothing twice',()=>{const s=completed();assert.deepEqual(step(s,'demo-confirm'),s)});
test('Partial confirmation does not claim full Spades format',()=>{const s=completed('spades',['maya']);assert.equal(C.points(s),35);assert.equal(s.metrics.fullCards,0);assert(!s.history[0].format)});
test('Host-reported guests cannot independently confirm format',()=>{let s=seed();s=step(s,'create',{a:'cards',venue:'table',minutes:20,total:4,with:3});s=step(s,'ready');s=step(s,'demo-fill');s=step(s,'demo-meet');s=step(s,'arrive');s=step(s,'demo-end');s=step(s,'report',{ids:C.group(s).members.filter(x=>x!=='you')});s=step(s,'demo-confirm');assert(!s.earned.includes('wild'))});
test('Pickleball third round grants Rally energy only',()=>{let s=completed('pickleball');assert.equal(C.points(s),85);assert(s.earned.includes('rally'))});
test('Locked equipment cannot be equipped',()=>assert.throws(()=>step(seed(),'equip',{id:'wild'}),/not been earned/));
test('Earned item equips and persists in state',()=>assert.equal(step(completed(),'equip',{id:'wild'}).equipped,'wild'));
test('Starter color and shape free',()=>{let s=step(seed(),'character',{color:'blue',shape:'square'});assert.equal(s.character.color,'blue');assert.equal(C.points(s),35)});
test('Unknown avatar option rejected',()=>assert.throws(()=>step(seed(),'character',{shape:'admin'}),/Unknown/));
test('Leaving reopens seat without losing points',()=>{let s=step(seed(),'join',{id:'spades'});s=step(s,'leave');assert.equal(s.active,null);assert.equal(C.count(C.group(s,'spades')),3);assert.equal(C.points(s),35)});
test('Host departure cancels listing',()=>{let s=step(seed(),'create',{a:'coffee',venue:'corner',minutes:10,total:4,with:1});const id=s.active;s=step(s,'leave');assert.equal(C.group(s,id).phase,'canceled')});
test('Four-person format rejects five seats',()=>assert.throws(()=>step(seed(),'create',{a:'cards',venue:'table',minutes:20,total:5,with:1}),/size/));
test('Creation validates activity-venue pairing',()=>assert.throws(()=>step(seed(),'create',{a:'pickle',venue:'table',minutes:20,total:4,with:1}),/suitable/));
test('At least one open spot required',()=>assert.throws(()=>step(seed(),'create',{a:'cards',venue:'table',minutes:20,total:4,with:4}),/open/));
test('No 30-minute or future calendar scheduling',()=>assert.throws(()=>step(seed(),'create',{a:'cards',venue:'table',minutes:30,total:4,with:1}),/20/));
test('Already-here invitation has honest ten-minute arrival window',()=>{const s=step(seed(),'create',{a:'cards',venue:'table',minutes:0,total:4,with:3});assert(C.group(s).hereNow);assert.equal(C.group(s).deadline,T+600000)});
test('Raw chat payload remains data',()=>{let s=step(seed(),'join',{id:'spades'});s=step(s,'chat',{text:'<img src=x onerror=alert(1)>'});assert.equal(C.group(s).chat[0].text,'<img src=x onerror=alert(1)>')});
test('Blank chat rejected',()=>assert.throws(()=>step(step(seed(),'join',{id:'spades'}),'chat',{text:' '}),/Write/));
test('Chat bounded to 500 chars',()=>{let s=step(seed(),'join',{id:'spades'});s=step(s,'chat',{text:'x'.repeat(700)});assert.equal(C.group(s).chat[0].text.length,500)});
test('Expired inventory leaves no completed records',()=>{let s=step(seed(),'advance',{minutes:21});assert.equal(C.search(s,{},T).length,0);assert.equal(s.history.length,0);assert.equal(C.points(s),35)});
test('Queue is explicit and expires after twenty minutes',()=>{let s=step(seed(),'queue',{ids:['coffee','walk']});assert(s.queue);s=step(s,'advance',{minutes:21});assert.equal(s.queue,null)});
test('Queue cannot select over three activities',()=>assert.throws(()=>step(seed(),'queue',{ids:['coffee','walk','cards','pickle']}),/three/));
test('Blocking hides relevant inventory and prevents joining',()=>{let s=step(seed(),'block',{id:'maya'});assert(!C.search(s,{},T).some(p=>p.id==='spades'));assert.throws(()=>step(s,'join',{id:'spades'}),/no longer/)});
test('Corrupt saved state is detectable',()=>{let s=seed();s.metrics.rounds=-1;assert(!C.validate(s))});
test('Failed transition does not mutate original state',()=>{const s=seed(),copy=JSON.stringify(s);assert.throws(()=>step(s,'join',{id:'fake'}));assert.equal(JSON.stringify(s),copy)});
console.log(JSON.stringify({suite:'Core invariants',passed:tests.filter(t=>t.pass).length,total:tests.length,tests},null,2));
