"""Real UI interactions. BASE_URL uses actual HTTP; otherwise exact standalone HTML.
No successful network test is inferred from inline testing.
"""
from playwright.sync_api import sync_playwright
from pathlib import Path
import os,json,traceback
ROOT=Path(__file__).resolve().parents[1]
BASE=os.environ.get('BASE_URL','')
rows=[]; errors=[]; pages=[]
def check(name, condition):
    if not condition: raise AssertionError(name)
    rows.append({'name':name,'pass':True})
def click(p,a,id=None,scope=''):
    p.locator(scope+'[data-action="'+a+'"]'+('[data-id="'+id+'"]' if id is not None else '')).first.click(timeout=6000)
def snapshot(p):return p.evaluate('RoundV5.snapshot()')
def points(p):return p.evaluate('Round5.ap(RoundV5.snapshot())')
def current(p):return p.evaluate('Round5.G(RoundV5.snapshot())')
def reset(p):p.evaluate('RoundV5.reset()')
def activity(p,name):
    click(p,'choose-filter-activity');p.locator('#pop-query').fill(name)
    p.locator('#pop-options .option').first.click()
def ss(p,n):p.screenshot(path=str(ROOT/'screens'/n),full_page=True)
with sync_playwright() as pw:
    exe=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium' if Path('/usr/bin/chromium').exists() else None)
    browser=pw.chromium.launch(headless=True,executable_path=exe,args=['--no-sandbox'])
    p=browser.new_page(viewport={'width':390,'height':844},accept_downloads=True)
    p.on('pageerror',lambda e:errors.append(str(e)))
    def load():
        if BASE:p.goto(BASE,wait_until='networkidle',timeout=60000)
        else:p.set_content((ROOT/'round_v5.html').read_text(),wait_until='load')
        p.wait_for_function('window.RoundV5 && RoundV5.version === "5.0.0"',timeout=15000)
    try:
        load()
        check('Document explicitly identifies V5',p.locator('meta[name="round-version"]').get_attribute('content')=='5.0.0')
        check('Six useful initial groups, not an endless feed',p.locator('.group-row').count()==6)
        check('No native select stack',p.locator('select').count()==0)
        check('No compulsory typing on primary finder',p.locator('#main input[type="search"]').count()==0)
        for w in [320,360,390,430,768,1024,1440]:
            p.set_viewport_size({'width':w,'height':960 if w>700 else 844})
            check('Finder no horizontal overflow at '+str(w),p.evaluate('document.documentElement.scrollWidth <= innerWidth+1'))
            if w<=430:
                overlap=p.evaluate("""() => [...document.querySelectorAll('.group-row')].some(r=>{let a=r.querySelector('.note').getBoundingClientRect(),b=r.querySelector('.group-right .btn').getBoundingClientRect();return a.bottom>b.top+1 && a.top<b.bottom-1 && a.right>b.left && a.left<b.right})""")
                check('No note/CTA overlap at '+str(w),not overlap)
        p.set_viewport_size({'width':1440,'height':1050});ss(p,'01-finder-desktop.png')
        p.set_viewport_size({'width':390,'height':844});ss(p,'02-finder-mobile.png')
        click(p,'choose-filter-activity');check('Dropdown announces expanded state',p.locator('[data-action="choose-filter-activity"]').get_attribute('aria-expanded')=='true')
        p.locator('#pop-query').fill('Spades');check('Picker retains typing focus',p.locator('#pop-query').evaluate('(e)=>document.activeElement===e'))
        check('Controlled vocabulary finds exact option',p.locator('#pop-options .option').count()==1)
        ss(p,'03-activity-picker.png')
        p.keyboard.press('ArrowDown');p.keyboard.press('Enter');check('Keyboard chooses the matching activity',p.locator('.group-row').count()==1 and p.locator('.group-row').get_attribute('data-group')=='g-spades')
        click(p,'choose-filter-activity');p.keyboard.press('Escape');check('Escape closes popover',p.locator('#picker').evaluate('(e)=>e.classList.contains("hidden")'))
        check('Focus returns to dropdown trigger',p.locator('[data-action="choose-filter-activity"]').evaluate('(e)=>document.activeElement===e'))
        activity(p,'Catan');check('No invented inventory for supported activity',p.locator('.group-row').count()==0)
        reset(p);click(p,'family','Sports');check('Dynamic ten-person basketball listed',p.locator('[data-group="g-hoops"]').inner_text().find('8 / 10')>=0)
        check('Dynamic twelve-person volleyball listed',p.locator('[data-group="g-volley"]').inner_text().find('10 / 12')>=0)
        ss(p,'04-sports-formats.png')
        reset(p);click(p,'filters');click(p,'filter-duration',scope='#dialog ')
        p.locator('#dialog [data-action="filter-duration"][data-value="30"]').click()
        click(p,'apply-filters',scope='#dialog ');check('Total-time filter does not ignore activity duration',p.locator('.group-row').count()==0)
        reset(p);click(p,'area');check('Area button opens real filter settings',p.locator('#dialog').evaluate('(e)=>e.open'));click(p,'close',scope='#dialog ')
        click(p,'detail','g-spades');check('Review has actual group format', '4' in p.locator('#dialog').inner_text())
        click(p,'inspect','p0',scope='#dialog ');check('Inspector belongs to selected person','Maya' in p.locator('#dialog').inner_text())
        check('Inspector has relevant activity record','spades rounds' in p.locator('#dialog').inner_text().lower())
        ss(p,'05-player-card.png')
        p.locator('#dialog [data-action="inspect-tab"][data-tab="Collection"]').click()
        check('Inspected collection remains person-specific','Maya’s collection' in p.locator('#dialog').inner_text())
        p.locator('#dialog [data-action="reward"]').first.click()
        check('Cannot equip another person’s earned item',p.locator('#dialog [data-action="wear"]').count()==0)
        click(p,'back',scope='#dialog ');click(p,'back',scope='#dialog ')
        click(p,'join','g-spades',scope='#dialog ')
        check('One affirmative join fills roster and means going',len(current(p)['members'])==4 and 'me' in current(p)['going'])
        check('Group becomes ready without a second ready form',current(p)['phase']=='ready')
        check('Join does not award points',points(p)==60)
        p.locator('#chat-input').fill('<img src=x onerror="window.BAD=1"> & hello')
        p.locator('#chat-form .send').click()
        check('Chat text rendered without executing HTML',p.evaluate('window.BAD===undefined') and p.locator('#messages img').count()==0)
        check('Message stored for actual active group','<img' in current(p)['chat'][-1]['text'])
        click(p,'sticker');check('Character wave saved as a sticker',current(p)['chat'][-1].get('kind')=='wave')
        reset(p);click(p,'detail','g-spades');click(p,'join','g-spades',scope='#dialog ')
        click(p,'quick','Hey everyone! See you there.')
        ss(p,'06-group-chat.png')
        click(p,'simMeet');click(p,'here');check('Self check-in has no reward authority',points(p)==60)
        click(p,'simFinish');check('First attendance report unchecked',p.locator('#dialog input[name="met"]:checked').count()==0)
        for id in ['p0','p1','p2']:p.locator('#dialog input[value="'+id+'"]').check()
        click(p,'save-report',scope='#dialog ');check('Self-report remains pending with no AP',current(p)['phase']=='pending' and points(p)==60)
        click(p,'simProof');check('Complete round has two correct unlocks, 135 AP',points(p)==135 and len(snapshot(p)['history'])==1)
        ss(p,'07-unlock.png')
        click(p,'wear-new',scope='#dialog ');check('Earned object changes equipped character',snapshot(p)['wear']!='none')
        p.evaluate("RoundV5.dispatch('simProof')");check('Repeated confirmation cannot farm AP',points(p)==135 and len(snapshot(p)['history'])==1)
        ss(p,'08-collection.png')
        click(p,'wardrobe');p.locator('#dialog [data-action="tone"][data-value="3"]').click();check('Base customization works freely',snapshot(p)['tone']==3)
        click(p,'close',scope='#dialog ')
        p.evaluate("RoundV5.go('group')");click(p,'completion');click(p,'memory',scope='#dialog ')
        with p.expect_download() as download:click(p,'export',scope='#dialog ')
        out=ROOT/'tests/keepsake.svg';download.value.save_as(str(out));text=out.read_text()
        check('Keepsake export omits person names and venue',all(x not in text for x in ['Maya','Riverside','Common Table']))
        check('Keepsake is explicitly fictional','FICTIONAL' in text.upper() or 'DEMO' in text.upper())
        reset(p);click(p,'create');click(p,'draft-activity',scope='#dialog ');p.locator('#pop-query').fill('Basketball');p.locator('#pop-options .option').first.click()
        check('Activity automatically reveals only relevant format control',p.locator('#dialog [data-action="draft-format"]').count()==1)
        click(p,'draft-format',scope='#dialog ');p.locator('#pop-options .option').filter(has_text='5 on 5').click()
        check('Five-on-five creation sets ten people','10 players, exactly' in p.locator('#dialog').inner_text())
        check('No 10/20/30 start-time choices',p.locator('#dialog [data-action*="time"]').count()==0)
        ss(p,'09-create-basketball.png')
        click(p,'publish',scope='#dialog ');check('Published local group preserves ten-person format',current(p)['cap']==10 and current(p)['format']==1)
        reset(p);click(p,'create');click(p,'draft-activity',scope='#dialog ');p.locator('#pop-query').fill('Coffee');p.locator('#pop-options .option').first.click()
        p.locator('#dialog details').evaluate('(e)=>e.open=true');click(p,'draft-mode','request',scope='#dialog ');click(p,'publish',scope='#dialog ')
        click(p,'simCandidate');check('Host sees real sample request without occupying capacity',len(current(p)['requests'])==1 and len(current(p)['members'])==1)
        click(p,'inspect-request');check('Host can inspect candidate before invitation',p.locator('#dialog [data-action="invite"]').count()==1)
        ss(p,'10-host-inspection.png')
        click(p,'invite',scope='#dialog ');check('Invitation is not acceptance',len(current(p)['members'])==1 and len(current(p)['invited'])==1)
        click(p,'simRSVP');check('Accepting candidate now occupies a place',len(current(p)['members'])==2 and len(current(p)['invited'])==0)
        reset(p);activity(p,'jam');click(p,'detail');click(p,'request',scope='#dialog ')
        check('Own request does not manufacture a place',snapshot(p)['active'] is None and snapshot(p)['pending'] is not None)
        click(p,'simHostAccept');check('Host invitation still requires own acceptance',snapshot(p)['active'] is None and snapshot(p)['pending']['phase']=='invited')
        click(p,'accept');check('Explicit acceptance joins intended group',snapshot(p)['active']=='g-jam')
        reset(p);click(p,'quickmatch');check('Quick match proposes but does not commit',snapshot(p)['active'] is None and p.locator('#dialog [data-action="detail"]').count()==1);click(p,'close',scope='#dialog ')
        p.evaluate("RoundV5.dispatch('advance',{minutes:21})");check('Expiry creates no fictional completed activity',p.locator('.group-row').count()==0 and len(snapshot(p)['history'])==0)
        reset(p);p.evaluate("RoundV5.go('you')")
        for w in [320,390,768,1440]:
            p.set_viewport_size({'width':w,'height':900});check('Collection no horizontal overflow at '+str(w),p.evaluate('document.documentElement.scrollWidth <= innerWidth+1'))
        p.set_viewport_size({'width':390,'height':844})
        if BASE:
            p.evaluate("RoundV5.dispatch('customize',{tone:4})");p.reload(wait_until='networkidle');check('Actual HTTP origin persists local state across reload',snapshot(p)['tone']==4)
        check('No JavaScript page errors',len(errors)==0)
    except Exception as e:
        rows.append({'name':'Flow failed','pass':False,'error':str(e),'trace':traceback.format_exc()})
        print(traceback.format_exc());p.screenshot(path=str(ROOT/'tests/failure.png'),full_page=True)
    finally:
        report={'version':'5.0.0','mode':'real HTTP origin' if BASE else 'standalone HTML via set_content','base_url':BASE or None,'passed':sum(r['pass'] for r in rows),'total':len(rows),'page_errors':errors,'tests':rows}
        (ROOT/'tests/browser-results.json').write_text(json.dumps(report,indent=2));print(json.dumps({k:v for k,v in report.items() if k!='tests'}));browser.close()
if any(not r['pass'] for r in rows) or errors:raise SystemExit(1)
